<center><h1 style="color:green">Binary Cross Entropy</center>

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<b>Python Implementation

In [3]:
np.log([0])

C:\Users\Hp\AppData\Local\Temp\ipykernel_3784\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [4]:
# tensorflow use this for cliping
epsilon = 1e-7 

In [5]:
np.log([1e-7])

array([-16.11809565])

In [6]:
y_pred

array([1, 1, 0, 0, 1])

In [7]:
y_predicted_new = [max(i,epsilon) for i in y_pred]
y_predicted_new

[1, 1, 1e-07, 1e-07, 1]

In [8]:
1-epsilon

0.9999999

In [9]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.9999999, 0.9999999, 1e-07, 1e-07, 0.9999999]

In [10]:
y_predicted_new = np.array(y_predicted_new)

In [11]:
np.log(y_predicted_new)

array([-1.00000005e-07, -1.00000005e-07, -1.61180957e+01, -1.61180957e+01,
       -1.00000005e-07])

In [12]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

8.059047875637068

In [13]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [14]:
log_loss(y_true, y_pred)

8.059047875637068

<b>TensorFlow Implementation

In [15]:
loss = tf.keras.losses.BinaryCrossentropy()
result = loss(y_true, y_pred)
print("Binary Crossentropy:", result.numpy())

Binary Crossentropy: 8.006334
